name: Build and Push to Docker Hub

on:
    push:
        branches:
            - master # Change if your default branch is different

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            # Step 1 — Checkout code
            - name: Checkout repository
              uses: actions/checkout@v4

            # Step 2 — Set up Docker Buildx (for multi-platform builds)
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            # Step 3 — Login to Docker Hub
            - name: Log in to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            # Step 4 — Build and push image
            - name: Build and push
              uses: docker/build-push-action@v6
              with:
                  context: .
                  file: ./Dockerfile
                  push: true
                  tags: |
                      ${{ secrets.DOCKERHUB_USERNAME }}/docker-image-node-01:latest
                      ${{ secrets.DOCKERHUB_USERNAME }}/docker-image-node-01:${{ github.sha }}

            # Step 5 — (Optional) Show Docker image digest
            - name: Image digest
              run: echo ${{ steps.build.outputs.digest }}